app:
  jwt:
    secret: ${JWT_SECRET:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA53VzmIVVZZWyNm266l82}
    duration-in-minutes: ${JWT_DURATION_MINUTES:60}
  cache:
    size: ${CACHE_SIZE:5}
  urls:
    posts: "https://jsonplaceholder.typicode.com/posts"
    users: "https://jsonplaceholder.typicode.com/users"
    albums: "https://jsonplaceholder.typicode.com/albums"

management:
  endpoint:
    health:
      probes:
        enabled: true

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:vk_backend_intern}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_by.default_null_ordering: last
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    generate-ddl: true