app:
  urls:
    posts: "https://jsonplaceholder.typicode.com/posts"
    users: "https://jsonplaceholder.typicode.com/users"
    albums: "https://jsonplaceholder.typicode.com/albums"
    comments: "https://jsonplaceholder.typicode.com/comments"

server:
  port: 8181

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/vk_backend_intern}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_by.default_null_ordering: last
        format_sql: true
    open-in-view: false
    show-sql: true
    generate-ddl: true