name: Docker Image CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [ opened, reopened ]
    branches:
      - main
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java + Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Maven clean install
        run: mvn clean install

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the Docker Image
        run: |
          docker build --tag ${{ secrets.DOCKER_USERNAME }}/vk_backend_intern:${GITHUB_REF_NAME//\//-}-${GITHUB_SHA::7} .
          docker push ${{ secrets.DOCKER_USERNAME }}/vk_backend_intern:${GITHUB_REF_NAME//\//-}-${GITHUB_SHA::7}

      - name: Push latest
        if: ${{ github.ref_name == 'main' || github.ref_name == 'master' }}
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/vk_backend_intern:${GITHUB_REF_NAME//\//-}-${GITHUB_SHA::7} ${{ secrets.DOCKER_USERNAME }}/vk_backend_intern:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/vk_backend_intern:latest